let
    Source = Excel.Workbook(File.Contents("C:\Users\Computer LAB\Downloads\Uncleaned_DS_jobs.xlsx"), null, true),
    Uncleaned_DS_jobs_Sheet = Source{[Item="Uncleaned_DS_jobs",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(Uncleaned_DS_jobs_Sheet, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"index", Int64.Type}, {"Job Title", type text}, {"Salary Estimate", type text}, {"Job Description", type text}, {"Rating", type number}, {"Company Name", type text}, {"Location", type text}, {"Headquarters", type any}, {"Size", type any}, {"Founded", Int64.Type}, {"Type of ownership", type any}, {"Industry", type any}, {"Sector", type any}, {"Revenue", type any}, {"Competitors", type any}}),
    #"Extracted Text Before Delimiter" = Table.TransformColumns(#"Changed Type", {{"Salary Estimate", each Text.BeforeDelimiter(_, "("), type text}}),
    #"Inserted Text Before Delimiter" = Table.AddColumn(#"Extracted Text Before Delimiter", "Text Before Delimiter", each Text.BeforeDelimiter([Salary Estimate], "-"), type text),
    #"Split Column by Delimiter" = Table.SplitColumn(#"Inserted Text Before Delimiter", "Salary Estimate", Splitter.SplitTextByDelimiter("-", QuoteStyle.Csv), {"Salary Estimate.1", "Salary Estimate.2"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Salary Estimate.1", type text}, {"Salary Estimate.2", type text}}),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type1",{"Text Before Delimiter"}),
    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Salary Estimate.1", "Min Salary"}, {"Salary Estimate.2", "Max Salary"}}),
    #"Added Custom" = Table.AddColumn(#"Renamed Columns", "Role Type", each if Text.Contains([Job Title], "Data Scientist") then
"Data Scientist"
else if Text.Contains([Job Title], "Data Analyst") then
"Data Analyst"
else if Text.Contains([Job Title], "Data Engineer") then
"Data Engineer"

else if Text.Contains([Job Title], "Machine Learning") then
"Machine Learning Engineer"
else
"other"),
    #"Reordered Columns" = Table.ReorderColumns(#"Added Custom",{"index", "Job Title", "Role Type", "Min Salary", "Max Salary", "Job Description", "Rating", "Company Name", "Location", "Headquarters", "Size", "Founded", "Type of ownership", "Industry", "Sector", "Revenue", "Competitors"}),
    #"Removed Columns1" = Table.RemoveColumns(#"Reordered Columns",{"Job Title"}),
    #"Added Custom1" = Table.AddColumn(#"Removed Columns1", "Location.1", each if [Location]= "New Jersey" then ", NJ"
else if [Location] = "Remote" then ", other"
else if [Location]= "United States" then ", other"
else if [Location]= "Texas" then ", TX"
else if [Location]= "Patuxent" then ", MA"
else if [Location]= "California" then ", CA"
else if [Location]= "Utah" then ", UT"
else [Location]),
    #"Reordered Columns1" = Table.ReorderColumns(#"Added Custom1",{"index", "Role Type", "Min Salary", "Max Salary", "Job Description", "Rating", "Company Name", "Location.1", "Location", "Headquarters", "Size", "Founded", "Type of ownership", "Industry", "Sector", "Revenue", "Competitors"}),
    #"Removed Columns2" = Table.RemoveColumns(#"Reordered Columns1",{"Location"}),
    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns2",{{"Location.1", "Location"}}),
    #"Split Column by Delimiter1" = Table.SplitColumn(#"Renamed Columns1", "Location", Splitter.SplitTextByDelimiter(",", QuoteStyle.Csv), {"Location.1", "Location.2"}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Split Column by Delimiter1",{{"Location.1", type text}, {"Location.2", type text}}),
    #"Renamed Columns2" = Table.RenameColumns(#"Changed Type2",{{"Location.2", "State Abbreviations"}, {"Location.1", "Location"}}),
    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns2","Anne Arundel","MA",Replacer.ReplaceText,{"State Abbreviations"}),
    #"Inserted Text Before Delimiter1" = Table.AddColumn(#"Replaced Value", "Text Before Delimiter", each Text.BeforeDelimiter([Size], " "), type text),
    #"Inserted Text Between Delimiters" = Table.AddColumn(#"Inserted Text Before Delimiter1", "Text Between Delimiters", each Text.BetweenDelimiters([Size], " ", " ", 1, 0), type text),
    #"Renamed Columns3" = Table.RenameColumns(#"Inserted Text Between Delimiters",{{"Text Before Delimiter", "Min Size Company"}, {"Text Between Delimiters", "Max Size Company"}}),
    #"Reordered Columns2" = Table.ReorderColumns(#"Renamed Columns3",{"index", "Role Type", "Min Salary", "Max Salary", "Job Description", "Rating", "Company Name", "Location", "State Abbreviations", "Headquarters", "Size", "Min Size Company", "Max Size Company", "Founded", "Type of ownership", "Industry", "Sector", "Revenue", "Competitors"}),
    #"Removed Columns3" = Table.RemoveColumns(#"Reordered Columns2",{"Size"}),
    #"Removed Blank Rows" = Table.SelectRows(#"Removed Columns3", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Removed Blank Rows", {"index", "Role Type", "Min Salary", "Max Salary", "Job Description", "Rating", "Company Name", "Location", "State Abbreviations", "Headquarters", "Min Size Company", "Max Size Company", "Founded", "Type of ownership", "Industry", "Sector", "Revenue", "Competitors"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Removed Errors",-1,"Others",Replacer.ReplaceValue,{"Industry"}),
    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1",-1,"Others",Replacer.ReplaceValue,{"Competitors"}),
    #"Inserted Text After Delimiter" = Table.AddColumn(#"Replaced Value2", "Text After Delimiter", each Text.AfterDelimiter([Company Name], "#(lf)"), type text),
    #"Removed Columns4" = Table.RemoveColumns(#"Inserted Text After Delimiter",{"Text After Delimiter"}),
    #"Split Column by Delimiter2" = Table.SplitColumn(#"Removed Columns4", "Company Name", Splitter.SplitTextByDelimiter("#(lf)", QuoteStyle.Csv), {"Company Name.1", "Company Name.2"}),
    #"Changed Type3" = Table.TransformColumnTypes(#"Split Column by Delimiter2",{{"Company Name.1", type text}, {"Company Name.2", type number}}),
    #"Removed Columns5" = Table.RemoveColumns(#"Changed Type3",{"Company Name.2", "Job Description"}),
    #"Renamed Columns4" = Table.RenameColumns(#"Removed Columns5",{{"Company Name.1", "Company Name"}}),
    #"Split Column by Delimiter3" = Table.SplitColumn(#"Renamed Columns4", "Min Salary", Splitter.SplitTextByDelimiter("$", QuoteStyle.Csv), {"Min Salary.1", "Min Salary.2"}),
    #"Changed Type4" = Table.TransformColumnTypes(#"Split Column by Delimiter3",{{"Min Salary.1", type text}, {"Min Salary.2", type text}}),
    #"Removed Columns6" = Table.RemoveColumns(#"Changed Type4",{"Min Salary.1"}),
    #"Inserted Text Before Delimiter2" = Table.AddColumn(#"Removed Columns6", "Text Before Delimiter", each Text.BeforeDelimiter([Min Salary.2], "K"), type text),
    #"Inserted Text Between Delimiters1" = Table.AddColumn(#"Inserted Text Before Delimiter2", "Text Between Delimiters", each Text.BetweenDelimiters([Max Salary], "$", "K"), type text),
    #"Reordered Columns3" = Table.ReorderColumns(#"Inserted Text Between Delimiters1",{"index", "Role Type", "Min Salary.2", "Text Before Delimiter", "Text Between Delimiters", "Max Salary", "Rating", "Company Name", "Location", "State Abbreviations", "Headquarters", "Min Size Company", "Max Size Company", "Founded", "Type of ownership", "Industry", "Sector", "Revenue", "Competitors"}),
    #"Removed Columns7" = Table.RemoveColumns(#"Reordered Columns3",{"Min Salary.2", "Max Salary"}),
    #"Renamed Columns5" = Table.RenameColumns(#"Removed Columns7",{{"Text Before Delimiter", "Min Salary"}, {"Text Between Delimiters", "Max Salary"}})
in
    #"Renamed Columns5"